import {
  User,
  MenuItem,
  AttendanceRecord,
  BillRecord,
  PaymentRecord,
  InventoryItem,
  Complaint,
  Notice,
  MessSettings
} from './types';

export const INITIAL_STUDENTS: User[] = [
  {
    id: 'std-prince',
    name: 'Prince Kumar',
    email: 'kumarprince3552@gmail.com',
    role: 'student',
    studentId: 'ST001',
    roomNo: 'H2-101',
    hostelBlock: 'Hostel 2 (Boys)',
    messHall: 'Hostel 2 Mess',
    phone: '+91 98765 43219',
    dietPreference: 'Veg',
    status: 'Active',
    year: '3rd Year',
    branch: 'Computer Science'
  },
  {
    id: 'std-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@hostel.edu',
    role: 'student',
    studentId: 'CS2023-014',
    roomNo: 'A-204',
    hostelBlock: 'Block A (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43210',
    dietPreference: 'Veg',
    status: 'Active',
    year: '3rd Year',
    branch: 'Computer Science'
  },
  {
    id: 'std-2',
    name: 'Diya Patel',
    email: 'diya.patel@hostel.edu',
    role: 'student',
    studentId: 'EC2023-088',
    roomNo: 'G-112',
    hostelBlock: 'Block G (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43211',
    dietPreference: 'Jain',
    status: 'Active',
    year: '2nd Year',
    branch: 'Electronics'
  },
  {
    id: 'std-3',
    name: 'Rohan Verma',
    email: 'rohan.verma@hostel.edu',
    role: 'student',
    studentId: 'ME2022-031',
    roomNo: 'B-305',
    hostelBlock: 'Block B (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43212',
    dietPreference: 'Non-Veg',
    status: 'Active',
    year: '4th Year',
    branch: 'Mechanical'
  },
  {
    id: 'std-4',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@hostel.edu',
    role: 'student',
    studentId: 'CS2024-009',
    roomNo: 'G-208',
    hostelBlock: 'Block G (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43213',
    dietPreference: 'Veg',
    status: 'Active',
    year: '1st Year',
    branch: 'Data Science'
  },
  {
    id: 'std-5',
    name: 'Vikramaditya Singh',
    email: 'vikram.singh@hostel.edu',
    role: 'student',
    studentId: 'EE2023-045',
    roomNo: 'A-102',
    hostelBlock: 'Block A (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43214',
    dietPreference: 'Non-Veg',
    status: 'Active',
    year: '3rd Year',
    branch: 'Electrical'
  },
  {
    id: 'std-6',
    name: 'Sneha Kulkarni',
    email: 'sneha.k@hostel.edu',
    role: 'student',
    studentId: 'CV2023-019',
    roomNo: 'H-310',
    hostelBlock: 'Block H (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43215',
    dietPreference: 'Veg',
    status: 'Active',
    year: '2nd Year',
    branch: 'Civil'
  },
  {
    id: 'std-7',
    name: 'Karan Mehra',
    email: 'karan.m@hostel.edu',
    role: 'student',
    studentId: 'CS2023-062',
    roomNo: 'B-108',
    hostelBlock: 'Block B (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43216',
    dietPreference: 'Non-Veg',
    status: 'On Leave',
    year: '3rd Year',
    branch: 'Computer Science'
  },
  {
    id: 'std-8',
    name: 'Pooja Nair',
    email: 'pooja.nair@hostel.edu',
    role: 'student',
    studentId: 'BT2024-002',
    roomNo: 'G-401',
    hostelBlock: 'Block G (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43217',
    dietPreference: 'Veg',
    status: 'Active',
    year: '1st Year',
    branch: 'Biotechnology'
  },
  {
    id: 'std-9',
    name: 'Aditya Gupta',
    email: 'aditya.g@hostel.edu',
    role: 'student',
    studentId: 'ME2023-054',
    roomNo: 'C-214',
    hostelBlock: 'Block C (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43218',
    dietPreference: 'Veg',
    status: 'Active',
    year: '2nd Year',
    branch: 'Mechanical'
  },
  {
    id: 'std-10',
    name: 'Ishaan Malhotra',
    email: 'ishaan.m@hostel.edu',
    role: 'student',
    studentId: 'CS2022-071',
    roomNo: 'A-405',
    hostelBlock: 'Block A (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43219',
    dietPreference: 'Non-Veg',
    status: 'Active',
    year: '4th Year',
    branch: 'Computer Science'
  },
  {
    id: 'std-11',
    name: 'Tanvi Deshmukh',
    email: 'tanvi.d@hostel.edu',
    role: 'student',
    studentId: 'CH2023-011',
    roomNo: 'H-105',
    hostelBlock: 'Block H (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43220',
    dietPreference: 'Jain',
    status: 'Active',
    year: '2nd Year',
    branch: 'Chemical'
  },
  {
    id: 'std-12',
    name: 'Manish Rawat',
    email: 'manish.r@hostel.edu',
    role: 'student',
    studentId: 'EE2024-032',
    roomNo: 'C-109',
    hostelBlock: 'Block C (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43221',
    dietPreference: 'Veg',
    status: 'Active',
    year: '1st Year',
    branch: 'Electrical'
  },
  {
    id: 'std-13',
    name: 'Rhea Sen',
    email: 'rhea.sen@hostel.edu',
    role: 'student',
    studentId: 'EC2023-024',
    roomNo: 'G-302',
    hostelBlock: 'Block G (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43222',
    dietPreference: 'Non-Veg',
    status: 'Active',
    year: '3rd Year',
    branch: 'Electronics'
  },
  {
    id: 'std-14',
    name: 'Gaurav Joshi',
    email: 'gaurav.j@hostel.edu',
    role: 'student',
    studentId: 'CS2023-099',
    roomNo: 'B-212',
    hostelBlock: 'Block B (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43223',
    dietPreference: 'Veg',
    status: 'Active',
    year: '2nd Year',
    branch: 'Computer Science'
  },
  {
    id: 'std-15',
    name: 'Neha Choudhary',
    email: 'neha.c@hostel.edu',
    role: 'student',
    studentId: 'CV2022-044',
    roomNo: 'H-202',
    hostelBlock: 'Block H (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43224',
    dietPreference: 'Veg',
    status: 'Inactive',
    year: '4th Year',
    branch: 'Civil'
  },
  {
    id: 'std-16',
    name: 'Siddharth Rao',
    email: 'siddharth.r@hostel.edu',
    role: 'student',
    studentId: 'ME2024-018',
    roomNo: 'A-312',
    hostelBlock: 'Block A (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43225',
    dietPreference: 'Non-Veg',
    status: 'Active',
    year: '1st Year',
    branch: 'Mechanical'
  },
  {
    id: 'std-17',
    name: 'Meera Nambiar',
    email: 'meera.n@hostel.edu',
    role: 'student',
    studentId: 'BT2023-015',
    roomNo: 'G-115',
    hostelBlock: 'Block G (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43226',
    dietPreference: 'Veg',
    status: 'Active',
    year: '2nd Year',
    branch: 'Biotechnology'
  },
  {
    id: 'std-18',
    name: 'Prateek Jain',
    email: 'prateek.j@hostel.edu',
    role: 'student',
    studentId: 'CS2023-118',
    roomNo: 'B-408',
    hostelBlock: 'Block B (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43227',
    dietPreference: 'Jain',
    status: 'Active',
    year: '3rd Year',
    branch: 'Computer Science'
  },
  {
    id: 'std-19',
    name: 'Simran Gill',
    email: 'simran.g@hostel.edu',
    role: 'student',
    studentId: 'EC2024-006',
    roomNo: 'H-409',
    hostelBlock: 'Block H (Girls)',
    messHall: 'Vindhya Dining',
    phone: '+91 98765 43228',
    dietPreference: 'Non-Veg',
    status: 'Active',
    year: '1st Year',
    branch: 'Electronics'
  },
  {
    id: 'std-20',
    name: 'Harsh Vardhan',
    email: 'harsh.v@hostel.edu',
    role: 'student',
    studentId: 'EE2022-089',
    roomNo: 'C-301',
    hostelBlock: 'Block C (Boys)',
    messHall: 'Annapurna Hall',
    phone: '+91 98765 43229',
    dietPreference: 'Veg',
    status: 'Active',
    year: '4th Year',
    branch: 'Electrical'
  }
];

export const INITIAL_MANAGERS: User[] = [
  {
    id: 'mgr-1',
    name: 'Rajesh Kumar Pandey',
    email: 'rajesh.pandey@hostel.edu',
    role: 'manager',
    phone: '+91 98111 22334',
    messHall: 'Annapurna Hall (Main Boys Mess)',
    status: 'Active',
    branch: 'Day Shift (6:30 AM - 3:30 PM)'
  },
  {
    id: 'mgr-2',
    name: 'Sunita Radhakrishnan',
    email: 'sunita.r@hostel.edu',
    role: 'manager',
    phone: '+91 98222 33445',
    messHall: 'Vindhya Dining (Girls Hostel Mess)',
    status: 'Active',
    branch: 'General Shift (7:00 AM - 4:00 PM)'
  },
  {
    id: 'mgr-3',
    name: 'Mohan Lal Verma',
    email: 'mohan.verma@hostel.edu',
    role: 'manager',
    phone: '+91 98333 44556',
    messHall: 'Kaveri Annex & Night Canteen',
    status: 'Active',
    branch: 'Evening Shift (3:00 PM - 11:30 PM)'
  }
];

export const INITIAL_ADMIN: User = {
  id: 'admin-1',
  name: 'Prof. Ramesh Chandra',
  email: 'chief.warden@hostel.edu',
  role: 'admin',
  phone: '+91 98000 11223',
  messHall: 'Central Hostel Administration',
  status: 'Active'
};

export const INITIAL_MENUS: MenuItem[] = [
  // Monday (Today's Menu: Aalu Paratha & Dahi; Chawal, Masoor Dal & Mausami Sabji; Ice Cream; Roti, Chawal & Mausami Sabji)
  {
    id: 'm-mon-bf',
    name: 'Aalu Paratha with Dahi & Sauce',
    category: 'Breakfast',
    items: ['Aalu Paratha', 'Dahi (1 dabu)', 'Sauce'],
    timing: '7:30 AM - 9:30 AM',
    calories: 460,
    dietType: 'Veg',
    dayOfWeek: 'Monday'
  },
  {
    id: 'm-mon-lu',
    name: 'Chawal, Masoor Dal & Mausami Sabji',
    category: 'Lunch',
    items: ['Chawal', 'Masoor Dal', 'Mausami Sabji', 'Chips'],
    timing: '12:30 PM - 2:30 PM',
    calories: 640,
    dietType: 'Veg',
    dayOfWeek: 'Monday'
  },
  {
    id: 'm-mon-sn',
    name: 'Ice Cream Special (Poha + Sev + Lemon Tea)',
    category: 'Snacks',
    items: ['Ice Cream', 'Poha + Sev + Lemon Tea'],
    timing: '5:00 PM - 6:30 PM',
    calories: 220,
    dietType: 'Veg',
    dayOfWeek: 'Monday'
  },
  {
    id: 'm-mon-di',
    name: 'Roti, Chawal & Mausami Sabji',
    category: 'Dinner',
    items: ['Roti', 'Chawal', 'Mausami Sabji', 'Salaad', 'Channa Fry Daal'],
    timing: '8:00 PM - 10:00 PM',
    calories: 610,
    dietType: 'Veg',
    dayOfWeek: 'Monday'
  },

  // Tuesday
  {
    id: 'm-tue-bf',
    name: 'Idli, Sambhar & Badam Chutni',
    category: 'Breakfast',
    items: ['Idli', 'Sambhar', 'Badam Chutni'],
    timing: '7:30 AM - 9:30 AM',
    calories: 390,
    dietType: 'Veg',
    dayOfWeek: 'Tuesday'
  },
  {
    id: 'm-tue-lu',
    name: 'Chawal, Masoor Daal & Aalu Soyabean',
    category: 'Lunch',
    items: ['Chawal', 'Masoor Daal', 'Aalu Soyabean Sukha Sabji', 'Salaad'],
    timing: '12:30 PM - 2:30 PM',
    calories: 630,
    dietType: 'Veg',
    dayOfWeek: 'Tuesday'
  },
  {
    id: 'm-tue-sn',
    name: 'Evening Tea & Biscuits',
    category: 'Snacks',
    items: ['Chai (Tea)', 'Biscuits'],
    timing: '5:00 PM - 6:30 PM',
    calories: 160,
    dietType: 'Veg',
    dayOfWeek: 'Tuesday'
  },
  {
    id: 'm-tue-di',
    name: 'Kheer, Poori & Kabooli Chana Sabji',
    category: 'Dinner',
    items: ['Kheer', 'Poori', 'Kabooli Chana Sabji', 'Zeera Rice'],
    timing: '8:00 PM - 10:00 PM',
    calories: 740,
    dietType: 'Special',
    dayOfWeek: 'Tuesday'
  },

  // Wednesday
  {
    id: 'm-wed-bf',
    name: 'Saada Paratha, Omelette / Misti Dahi & Banana',
    category: 'Breakfast',
    items: ['Aamlet (1 pc) / Misti Dahi', 'Saada Paratha', 'Mattar Chola', '3 Bananas'],
    timing: '7:30 AM - 9:30 AM',
    calories: 520,
    dietType: 'Special',
    dayOfWeek: 'Wednesday'
  },
  {
    id: 'm-wed-lu',
    name: 'Chawal, Chana Daal Fry & Sabji',
    category: 'Lunch',
    items: ['Chawal', 'Chana Daal Fry', 'Mausami Sabji', 'Chips / Papad', 'Salaad'],
    timing: '12:30 PM - 2:30 PM',
    calories: 650,
    dietType: 'Veg',
    dayOfWeek: 'Wednesday'
  },
  {
    id: 'm-wed-sn',
    name: 'Hot Pasta / Noodles',
    category: 'Snacks',
    items: ['Pasta / Noodles'],
    timing: '5:00 PM - 6:30 PM',
    calories: 270,
    dietType: 'Veg',
    dayOfWeek: 'Wednesday'
  },
  {
    id: 'm-wed-di',
    name: 'Chicken Curry / Paneer Masala Dinner',
    category: 'Dinner',
    items: ['Chicken (3 pcs) / Paneer Masala (Veg)', 'Chawal', 'Roti', 'Salaad'],
    timing: '8:00 PM - 10:00 PM',
    calories: 780,
    dietType: 'Non-Veg',
    dayOfWeek: 'Wednesday'
  },

  // Thursday
  {
    id: 'm-thu-bf',
    name: 'Milk, Cornflakes & Bread Jam',
    category: 'Breakfast',
    items: ['Milk (250 ml)', 'Cornflakes', 'Bread (2 pcs) + Jam'],
    timing: '7:30 AM - 9:30 AM',
    calories: 380,
    dietType: 'Veg',
    dayOfWeek: 'Thursday'
  },
  {
    id: 'm-thu-lu',
    name: 'Chawal, Bari Kadhi & Aaloo Bhujia',
    category: 'Lunch',
    items: ['Chawal', 'Bari Kadhi', 'Aaloo Bhujia', 'Chips'],
    timing: '12:30 PM - 2:30 PM',
    calories: 660,
    dietType: 'Veg',
    dayOfWeek: 'Thursday'
  },
  {
    id: 'm-thu-sn',
    name: 'Chilled Lassi / Maaza',
    category: 'Snacks',
    items: ['Lassi / Maaza'],
    timing: '5:00 PM - 6:30 PM',
    calories: 190,
    dietType: 'Veg',
    dayOfWeek: 'Thursday'
  },
  {
    id: 'm-thu-di',
    name: 'Veg Dum Biryani with Raita',
    category: 'Dinner',
    items: ['Veg Biriyani', 'Salaad', 'Rayata'],
    timing: '8:00 PM - 10:00 PM',
    calories: 680,
    dietType: 'Special',
    dayOfWeek: 'Thursday'
  },

  // Friday
  {
    id: 'm-fri-bf',
    name: 'Sattu Paratha with Chhola & Chatni',
    category: 'Breakfast',
    items: ['Sattu Paratha', 'Chhola', 'Chatni'],
    timing: '7:30 AM - 9:30 AM',
    calories: 510,
    dietType: 'Veg',
    dayOfWeek: 'Friday'
  },
  {
    id: 'm-fri-lu',
    name: 'Chawal, Chana Daal & Mausami Sabji',
    category: 'Lunch',
    items: ['Chawal', 'Chana Daal', 'Mausami Sabji', 'Aachar'],
    timing: '12:30 PM - 2:30 PM',
    calories: 630,
    dietType: 'Veg',
    dayOfWeek: 'Friday'
  },
  {
    id: 'm-fri-sn',
    name: 'Chai & Lays Chips',
    category: 'Snacks',
    items: ['Chai (Tea)', 'Lays Chips'],
    timing: '5:00 PM - 6:30 PM',
    calories: 220,
    dietType: 'Veg',
    dayOfWeek: 'Friday'
  },
  {
    id: 'm-fri-di',
    name: 'Fish Curry / Veg Mutter Paneer & Sponge Rasgulla',
    category: 'Dinner',
    items: ['Fish (3 pcs) / Veg Mutter Paneer (5 pcs)', 'Roti', 'Chawal', '1 Sponge Rasgulla (for veg)'],
    timing: '8:00 PM - 10:00 PM',
    calories: 790,
    dietType: 'Non-Veg',
    dayOfWeek: 'Friday'
  },

  // Saturday
  {
    id: 'm-sat-bf',
    name: 'Bihari Litti, Aalu Chana Sabji & Jalebi',
    category: 'Breakfast',
    items: ['Litti', 'Aalu Chana Sabji', 'Jalebi'],
    timing: '7:30 AM - 9:30 AM',
    calories: 560,
    dietType: 'Veg',
    dayOfWeek: 'Saturday'
  },
  {
    id: 'm-sat-lu',
    name: 'Chawal, Masoor Daal & Aalu Chokha',
    category: 'Lunch',
    items: ['Chawal', 'Masoor Daal', 'Aalu Chokha', 'Aachar', 'Salad', 'Chips'],
    timing: '12:30 PM - 2:30 PM',
    calories: 640,
    dietType: 'Veg',
    dayOfWeek: 'Saturday'
  },
  {
    id: 'm-sat-sn',
    name: 'Bread Pakoda & Hot Chai',
    category: 'Snacks',
    items: ['Bread Pakoda', 'Tea'],
    timing: '5:00 PM - 6:30 PM',
    calories: 280,
    dietType: 'Veg',
    dayOfWeek: 'Saturday'
  },
  {
    id: 'm-sat-di',
    name: 'Roti, Aalu Mausami Sabji & Booniya',
    category: 'Dinner',
    items: ['Roti', 'Aalu Mausami Sabji', 'Booniya (Sweet)'],
    timing: '8:00 PM - 10:00 PM',
    calories: 610,
    dietType: 'Veg',
    dayOfWeek: 'Saturday'
  },

  // Sunday
  {
    id: 'm-sun-bf',
    name: 'Dosa, Sambhar & Chutney',
    category: 'Breakfast',
    items: ['Dosa', 'Sambhar', 'Chutney'],
    timing: '7:30 AM - 9:30 AM',
    calories: 430,
    dietType: 'Veg',
    dayOfWeek: 'Sunday'
  },
  {
    id: 'm-sun-lu',
    name: 'Chawal, Chana Daal Fry & Aalu Chana',
    category: 'Lunch',
    items: ['Chawal', 'Chana Daal Fry', 'Aalu Chana Sabji', 'Salaad'],
    timing: '12:30 PM - 2:30 PM',
    calories: 670,
    dietType: 'Veg',
    dayOfWeek: 'Sunday'
  },
  {
    id: 'm-sun-sn',
    name: 'Samosa (2 pcs) with Chutney & Chai',
    category: 'Snacks',
    items: ['Samosa (2 pcs)', 'Chutney / Ketchup', 'Chai'],
    timing: '5:00 PM - 6:30 PM',
    calories: 320,
    dietType: 'Veg',
    dayOfWeek: 'Sunday'
  },
  {
    id: 'm-sun-di',
    name: 'Chicken Fry / Mushroom & Jeera Rice',
    category: 'Dinner',
    items: ['Chicken (3 pcs) Fry / Mushroom (Veg)', 'Jeera Chawal', 'Roti'],
    timing: '8:00 PM - 10:00 PM',
    calories: 810,
    dietType: 'Special',
    dayOfWeek: 'Sunday'
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Basmati Rice Premium (Kolam)',
    category: 'Grains & Pulses',
    quantity: 450,
    unit: 'kg',
    minimumStock: 200,
    status: 'In Stock',
    lastRestocked: '2026-09-12',
    supplier: 'Kisan Agro Traders',
    costPerUnit: 52
  },
  {
    id: 'inv-2',
    name: 'Whole Wheat Atta (Aashirvaad)',
    category: 'Grains & Pulses',
    quantity: 380,
    unit: 'kg',
    minimumStock: 150,
    status: 'In Stock',
    lastRestocked: '2026-09-10',
    supplier: 'Kisan Agro Traders',
    costPerUnit: 38
  },
  {
    id: 'inv-3',
    name: 'Toor Dal Desi Grade A',
    category: 'Grains & Pulses',
    quantity: 65,
    unit: 'kg',
    minimumStock: 100,
    status: 'Low Stock',
    lastRestocked: '2026-09-02',
    supplier: 'Shree Laxmi Pulses',
    costPerUnit: 145
  },
  {
    id: 'inv-4',
    name: 'Fresh Dairy Milk (Full Cream)',
    category: 'Dairy & Poultry',
    quantity: 120,
    unit: 'liters',
    minimumStock: 100,
    status: 'In Stock',
    lastRestocked: '2026-09-15',
    supplier: 'Amul Dairy Booth #14',
    costPerUnit: 64
  },
  {
    id: 'inv-5',
    name: 'Fresh Paneer Malai Blocks',
    category: 'Dairy & Poultry',
    quantity: 18,
    unit: 'kg',
    minimumStock: 25,
    status: 'Low Stock',
    lastRestocked: '2026-09-14',
    supplier: 'Amul Dairy Booth #14',
    costPerUnit: 340
  },
  {
    id: 'inv-6',
    name: 'Farm Fresh Eggs (Crate 30 pcs)',
    category: 'Dairy & Poultry',
    quantity: 42,
    unit: 'dozen',
    minimumStock: 30,
    status: 'In Stock',
    lastRestocked: '2026-09-13',
    supplier: 'National Egg Traders',
    costPerUnit: 78
  },
  {
    id: 'inv-7',
    name: 'Potatoes (Nashik Red)',
    category: 'Vegetables & Fruits',
    quantity: 260,
    unit: 'kg',
    minimumStock: 120,
    status: 'In Stock',
    lastRestocked: '2026-09-14',
    supplier: 'Mandi Wholesale Market',
    costPerUnit: 22
  },
  {
    id: 'inv-8',
    name: 'Red Onions (Grade 1)',
    category: 'Vegetables & Fruits',
    quantity: 210,
    unit: 'kg',
    minimumStock: 120,
    status: 'In Stock',
    lastRestocked: '2026-09-14',
    supplier: 'Mandi Wholesale Market',
    costPerUnit: 32
  },
  {
    id: 'inv-9',
    name: 'Tomatoes Hybrid Salad',
    category: 'Vegetables & Fruits',
    quantity: 35,
    unit: 'kg',
    minimumStock: 50,
    status: 'Low Stock',
    lastRestocked: '2026-09-13',
    supplier: 'Mandi Wholesale Market',
    costPerUnit: 28
  },
  {
    id: 'inv-10',
    name: 'Sunflower Refined Cooking Oil',
    category: 'Oils & Fats',
    quantity: 140,
    unit: 'liters',
    minimumStock: 80,
    status: 'In Stock',
    lastRestocked: '2026-09-08',
    supplier: 'Fortune Distributors',
    costPerUnit: 125
  },
  {
    id: 'inv-11',
    name: 'Pure Desi Cow Ghee',
    category: 'Oils & Fats',
    quantity: 8,
    unit: 'liters',
    minimumStock: 15,
    status: 'Low Stock',
    lastRestocked: '2026-08-28',
    supplier: 'Fortune Distributors',
    costPerUnit: 620
  },
  {
    id: 'inv-12',
    name: 'Commercial LPG Cylinders (19kg)',
    category: 'Gas & Fuel',
    quantity: 2,
    unit: 'cylinders',
    minimumStock: 6,
    status: 'Low Stock',
    lastRestocked: '2026-09-01',
    supplier: 'Indane Gas Agency',
    costPerUnit: 1850
  },
  {
    id: 'inv-13',
    name: 'Tea Leaves CTC Premium (Tata Tea)',
    category: 'Beverages & Snacks',
    quantity: 24,
    unit: 'kg',
    minimumStock: 20,
    status: 'In Stock',
    lastRestocked: '2026-09-05',
    supplier: 'Metro Cash & Carry',
    costPerUnit: 320
  },
  {
    id: 'inv-14',
    name: 'Iodized Crystal & Table Salt',
    category: 'Spices & Condiments',
    quantity: 80,
    unit: 'kg',
    minimumStock: 40,
    status: 'In Stock',
    lastRestocked: '2026-09-02',
    supplier: 'Tata Consumer',
    costPerUnit: 24
  },
  {
    id: 'inv-15',
    name: 'Turmeric Powder (Haldi Pure)',
    category: 'Spices & Condiments',
    quantity: 14,
    unit: 'kg',
    minimumStock: 15,
    status: 'Low Stock',
    lastRestocked: '2026-08-20',
    supplier: 'MDH Spices',
    costPerUnit: 210
  },
  {
    id: 'inv-16',
    name: 'Dishwashing Liquid & Powder',
    category: 'Cleaning & Hygiene',
    quantity: 0,
    unit: 'liters',
    minimumStock: 30,
    status: 'Out of Stock',
    lastRestocked: '2026-08-15',
    supplier: 'Vim Commercial Supplies',
    costPerUnit: 90
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-101',
    title: 'Undercooked Chapati in Dinner',
    description: 'The rotis served on Monday night dinner at Annapurna Hall were raw in the center and thick. Please instruct the kitchen staff to cook them properly.',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    rollNo: 'CS2023-014',
    date: '2026-09-14',
    category: 'Food Quality',
    status: 'In Progress',
    priority: 'Medium',
    resolutionNotes: 'Notified head chef Mohan. Rolling thickness recalibrated.'
  },
  {
    id: 'cmp-102',
    title: 'Water Cooler 2 Filter Smells Musty',
    description: 'The drinking water cooler in the Annapurna dining hall entrance has a bad odor. Please replace the RO candle filter immediately.',
    studentId: 'std-3',
    studentName: 'Rohan Verma',
    rollNo: 'ME2022-031',
    date: '2026-09-15',
    category: 'Infrastructure & Water',
    status: 'Pending',
    priority: 'High'
  },
  {
    id: 'cmp-103',
    title: 'More Pure Jain Counter Options Needed',
    description: 'Sometimes the root vegetables like onion and garlic get accidentally cross-contaminated on the buffet line. We need a separated serving ladle for Jain counter.',
    studentId: 'std-2',
    studentName: 'Diya Patel',
    rollNo: 'EC2023-088',
    date: '2026-09-11',
    category: 'Special Diet Request',
    status: 'Resolved',
    priority: 'High',
    resolutionNotes: 'Separated green-coded spoons and a dedicated counter partitioned at Vindhya dining.',
    resolvedAt: '2026-09-13'
  },
  {
    id: 'cmp-104',
    title: 'Breakfast Sambar was Served Cold',
    description: 'Arrived at 8:45 AM for breakfast today and the sambar dispenser was turned off, leading to cold sambar.',
    studentId: 'std-5',
    studentName: 'Vikramaditya Singh',
    rollNo: 'EE2023-045',
    date: '2026-09-13',
    category: 'Food Quality',
    status: 'Resolved',
    priority: 'Low',
    resolutionNotes: 'Heating induction repaired and warmer maintained continuously until 9:30 AM.',
    resolvedAt: '2026-09-14'
  },
  {
    id: 'cmp-105',
    title: 'Breakfast Timing Clashes with 8 AM Lab',
    description: 'Students having 8 AM electrical labs find 7:30 AM start too tight if there is a queue. Can the counter open 15 minutes early at 7:15 AM?',
    studentId: 'std-12',
    studentName: 'Manish Rawat',
    rollNo: 'EE2024-032',
    date: '2026-09-15',
    category: 'Mess Timings',
    status: 'Pending',
    priority: 'Medium'
  },
  {
    id: 'cmp-106',
    title: 'Rude Behavior by Evening Tea Staff',
    description: 'One of the temporary servers was shouting at students asking for extra biscuits during 5 PM tea.',
    studentId: 'std-6',
    studentName: 'Sneha Kulkarni',
    rollNo: 'CV2023-019',
    date: '2026-09-12',
    category: 'Staff Behavior',
    status: 'In Progress',
    priority: 'Medium',
    resolutionNotes: 'Manager Sunita had a counseling session with the vendor staff.'
  }
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'Ganesh Chaturthi Festive Feast on Friday Dinner',
    description: 'There will be a special festive banquet dinner on Friday, September 18th featuring Puran Poli, Modak, Paneer Kofta, and Basundi. Mess timing extended till 10:30 PM.',
    date: '2026-09-15',
    postedBy: 'Chief Warden Prof. Ramesh Chandra',
    authorRole: 'Admin',
    priority: 'Important',
    targetAudience: 'All'
  },
  {
    id: 'not-2',
    title: 'Mess Cut (Leave Rebate) Application Window',
    description: 'Students going home for the upcoming mid-semester break must submit their mess rebate applications on the portal at least 48 hours prior to departure to get billed deductions.',
    date: '2026-09-14',
    postedBy: 'Mess Committee Secretary',
    authorRole: 'Admin',
    priority: 'Normal',
    targetAudience: 'Students'
  },
  {
    id: 'not-3',
    title: 'Kitchen Deep Sanitization & Pest Control on Sunday Afternoon',
    description: 'Both Annapurna and Vindhya kitchens will undergo routine chemical fogging and sanitization between 2:45 PM and 4:45 PM this Sunday. Evening tea will resume on time at 5:00 PM.',
    date: '2026-09-12',
    postedBy: 'Rajesh Pandey (Mess Manager)',
    authorRole: 'Mess Manager',
    priority: 'Normal',
    targetAudience: 'All'
  },
  {
    id: 'not-4',
    title: 'Strict Hygiene Directive: Clean Your Trays at Segregation Counter',
    description: 'All hostel inmates are strictly requested to dump food remnants into the bio-waste bin and stack steel plates separately. CCTV monitored; spot fines will apply for littering.',
    date: '2026-09-10',
    postedBy: 'Hostel Administration',
    authorRole: 'Admin',
    priority: 'Urgent',
    targetAudience: 'Students'
  }
];

export const INITIAL_BILLS: BillRecord[] = [
  // Prince Kumar (Canonical Student ST001)
  {
    id: 'bill-prince-sep',
    studentId: 'std-prince',
    studentName: 'Prince Kumar',
    rollNo: 'ST001',
    roomNo: 'H2-101',
    hostelBlock: 'Hostel 2 (Boys)',
    month: 'September 2026',
    monthNum: 9,
    monthName: 'September 2026',
    year: 2026,
    breakfastCount: 22,
    lunchCount: 24,
    snacksCount: 20,
    dinnerCount: 23,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 440,
    lunchAmount: 960,
    snacksAmount: 300,
    dinnerAmount: 920,
    subtotal: 2620,
    adjustment: 0,
    totalAmount: 2620,
    paidAmount: 0,
    dueAmount: 2620,
    totalMeals: 89,
    status: 'PENDING',
    dueDate: '2026-10-05',
    generatedAt: '2026-09-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  {
    id: 'bill-prince-aug',
    studentId: 'std-prince',
    studentName: 'Prince Kumar',
    rollNo: 'ST001',
    roomNo: 'H2-101',
    hostelBlock: 'Hostel 2 (Boys)',
    month: 'August 2026',
    monthNum: 8,
    monthName: 'August 2026',
    year: 2026,
    breakfastCount: 21,
    lunchCount: 22,
    snacksCount: 20,
    dinnerCount: 22,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 420,
    lunchAmount: 880,
    snacksAmount: 300,
    dinnerAmount: 880,
    subtotal: 2480,
    adjustment: 0,
    totalAmount: 2480,
    paidAmount: 2480,
    dueAmount: 0,
    totalMeals: 85,
    status: 'PAID',
    paidAt: '2026-08-28T14:30:00Z',
    paidByName: 'Suresh Verma (Manager)',
    dueDate: '2026-09-05',
    generatedAt: '2026-08-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  {
    id: 'bill-prince-jul',
    studentId: 'std-prince',
    studentName: 'Prince Kumar',
    rollNo: 'ST001',
    roomNo: 'H2-101',
    hostelBlock: 'Hostel 2 (Boys)',
    month: 'July 2026',
    monthNum: 7,
    monthName: 'July 2026',
    year: 2026,
    breakfastCount: 22,
    lunchCount: 23,
    snacksCount: 21,
    dinnerCount: 22,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 440,
    lunchAmount: 920,
    snacksAmount: 315,
    dinnerAmount: 880,
    subtotal: 2555,
    adjustment: -5,
    adjustmentReason: 'Round-off adjustment',
    totalAmount: 2550,
    paidAmount: 2550,
    dueAmount: 0,
    totalMeals: 88,
    status: 'PAID',
    paidAt: '2026-07-29T16:00:00Z',
    paidByName: 'Suresh Verma (Manager)',
    dueDate: '2026-08-05',
    generatedAt: '2026-07-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  // Other students
  {
    id: 'bill-sep-01',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    rollNo: 'CS2023-014',
    roomNo: 'A-204',
    hostelBlock: 'Block A (Boys)',
    month: 'September 2026',
    monthNum: 9,
    monthName: 'September 2026',
    year: 2026,
    breakfastCount: 23,
    lunchCount: 24,
    snacksCount: 21,
    dinnerCount: 24,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 460,
    lunchAmount: 960,
    snacksAmount: 315,
    dinnerAmount: 960,
    subtotal: 2695,
    adjustment: 0,
    totalAmount: 2695,
    paidAmount: 0,
    dueAmount: 2695,
    totalMeals: 92,
    status: 'PENDING',
    dueDate: '2026-10-05',
    generatedAt: '2026-09-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  {
    id: 'bill-sep-02',
    studentId: 'std-2',
    studentName: 'Diya Patel',
    rollNo: 'EC2023-088',
    roomNo: 'G-112',
    hostelBlock: 'Block G (Girls)',
    month: 'September 2026',
    monthNum: 9,
    monthName: 'September 2026',
    year: 2026,
    breakfastCount: 24,
    lunchCount: 24,
    snacksCount: 22,
    dinnerCount: 23,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 480,
    lunchAmount: 960,
    snacksAmount: 330,
    dinnerAmount: 920,
    subtotal: 2690,
    adjustment: -100,
    adjustmentReason: 'Approved medical leave rebate',
    totalAmount: 2590,
    paidAmount: 2590,
    dueAmount: 0,
    totalMeals: 93,
    status: 'PAID',
    paidAt: '2026-09-10T11:00:00Z',
    paidByName: 'Suresh Verma (Manager)',
    dueDate: '2026-10-05',
    generatedAt: '2026-09-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  {
    id: 'bill-sep-03',
    studentId: 'std-3',
    studentName: 'Rohan Verma',
    rollNo: 'ME2022-031',
    roomNo: 'A-312',
    hostelBlock: 'Block A (Boys)',
    month: 'September 2026',
    monthNum: 9,
    monthName: 'September 2026',
    year: 2026,
    breakfastCount: 20,
    lunchCount: 22,
    snacksCount: 18,
    dinnerCount: 21,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 400,
    lunchAmount: 880,
    snacksAmount: 270,
    dinnerAmount: 840,
    subtotal: 2390,
    adjustment: 0,
    totalAmount: 2390,
    paidAmount: 0,
    dueAmount: 2390,
    totalMeals: 81,
    status: 'PENDING',
    dueDate: '2026-10-05',
    generatedAt: '2026-09-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  {
    id: 'bill-sep-04',
    studentId: 'std-4',
    studentName: 'Ananya Iyer',
    rollNo: 'CS2024-009',
    roomNo: 'B-215',
    hostelBlock: 'Block B (Girls)',
    month: 'September 2026',
    monthNum: 9,
    monthName: 'September 2026',
    year: 2026,
    breakfastCount: 22,
    lunchCount: 23,
    snacksCount: 21,
    dinnerCount: 22,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 440,
    lunchAmount: 920,
    snacksAmount: 315,
    dinnerAmount: 880,
    subtotal: 2555,
    adjustment: 0,
    totalAmount: 2555,
    paidAmount: 2555,
    dueAmount: 0,
    totalMeals: 88,
    status: 'PAID',
    paidAt: '2026-09-12T15:30:00Z',
    paidByName: 'Suresh Verma (Manager)',
    dueDate: '2026-10-05',
    generatedAt: '2026-09-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  },
  {
    id: 'bill-sep-05',
    studentId: 'std-5',
    studentName: 'Vikramaditya Singh',
    rollNo: 'EE2023-045',
    roomNo: 'C-401',
    hostelBlock: 'Block C (Boys)',
    month: 'September 2026',
    monthNum: 9,
    monthName: 'September 2026',
    year: 2026,
    breakfastCount: 21,
    lunchCount: 22,
    snacksCount: 19,
    dinnerCount: 22,
    breakfastRate: 20,
    lunchRate: 40,
    snacksRate: 15,
    dinnerRate: 40,
    breakfastAmount: 420,
    lunchAmount: 880,
    snacksAmount: 285,
    dinnerAmount: 880,
    subtotal: 2465,
    adjustment: 50,
    adjustmentReason: 'Late notice penalty',
    totalAmount: 2515,
    paidAmount: 0,
    dueAmount: 2515,
    totalMeals: 84,
    status: 'PENDING',
    dueDate: '2026-10-05',
    generatedAt: '2026-09-01T09:00:00Z',
    generatedByName: 'Suresh Verma (Manager)',
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-101',
    transactionId: 'TXN-9842145521',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    rollNo: 'CS2023-014',
    billId: 'bill-sep-01',
    amount: 4080,
    date: '2026-09-14',
    method: 'Counter Cash',
    status: 'Completed',
    referenceNo: 'CASH-REC-H2-001'
  },
  {
    id: 'pay-102',
    transactionId: 'TXN-9842145522',
    studentId: 'std-4',
    studentName: 'Ananya Iyer',
    rollNo: 'CS2024-009',
    billId: 'bill-sep-04',
    amount: 3830,
    date: '2026-09-12',
    method: 'Bank Challan',
    status: 'Completed',
    referenceNo: 'CHALLAN-SBI-5522'
  },
  {
    id: 'pay-103',
    transactionId: 'TXN-9842145523',
    studentId: 'std-6',
    studentName: 'Sneha Kulkarni',
    rollNo: 'CV2023-019',
    billId: 'bill-sep-06',
    amount: 3465,
    date: '2026-09-11',
    method: 'Cash',
    status: 'Completed',
    referenceNo: 'CASH-REC-H2-003'
  },
  {
    id: 'pay-104',
    transactionId: 'TXN-9842145524',
    studentId: 'std-3',
    studentName: 'Rohan Verma',
    rollNo: 'ME2022-031',
    billId: 'bill-sep-03',
    amount: 2000,
    date: '2026-09-15',
    method: 'Office Deposit',
    status: 'Completed',
    referenceNo: 'OFFICE-DEP-104'
  },
  {
    id: 'pay-105',
    transactionId: 'TXN-9842145525',
    studentId: 'std-8',
    studentName: 'Pooja Nair',
    rollNo: 'BT2024-002',
    billId: 'bill-sep-08',
    amount: 3900,
    date: '2026-09-13',
    method: 'Cash',
    status: 'Completed',
    referenceNo: 'CASH-REC-H2-005'
  },
  {
    id: 'pay-106',
    transactionId: 'TXN-9842145526',
    studentId: 'std-2',
    studentName: 'Diya Patel',
    rollNo: 'EC2023-088',
    billId: 'bill-sep-02',
    amount: 3600,
    date: '2026-09-15',
    method: 'Counter Cash',
    status: 'Pending',
    referenceNo: 'COUNTER-VERIF-REQ'
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-prince-16',
    studentId: 'std-prince',
    studentName: 'Prince Kumar',
    rollNo: 'ST001',
    roomNo: 'H2-101',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: false,
    dinner: true,
    totalPresent: 3,
    totalMeals: 4,
    hostelBlock: 'Hostel 2 (Boys)',
    breakfastDetail: { status: true, markedAt: '2026-09-16T08:30:00Z', markedBy: 'Manager Suresh Verma' },
    lunchDetail: { status: true, markedAt: '2026-09-16T13:15:00Z', markedBy: 'Manager Suresh Verma' },
    snacksDetail: { status: false, markedAt: '2026-09-16T17:45:00Z', markedBy: 'Manager Suresh Verma' },
    dinnerDetail: { status: true, markedAt: '2026-09-16T20:30:00Z', markedBy: 'Manager Suresh Verma' },
    updatedAt: '2026-09-16T20:32:00Z',
    updatedBy: 'Manager Suresh Verma'
  },
  // Historical records for Prince Kumar
  { id: 'att-prince-15', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-15', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-14', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-14', breakfast: true, lunch: true, snacks: false, dinner: true, totalPresent: 3, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-13', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-13', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-12', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-12', breakfast: false, lunch: true, snacks: true, dinner: true, totalPresent: 3, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-11', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-11', breakfast: true, lunch: true, snacks: true, dinner: false, totalPresent: 3, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-10', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-10', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-09', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-09', breakfast: true, lunch: true, snacks: false, dinner: true, totalPresent: 3, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-08', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-08', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-07', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-07', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-06', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-06', breakfast: false, lunch: true, snacks: true, dinner: true, totalPresent: 3, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-05', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-05', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-04', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-04', breakfast: true, lunch: false, snacks: true, dinner: true, totalPresent: 3, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  { id: 'att-prince-03', studentId: 'std-prince', studentName: 'Prince Kumar', rollNo: 'ST001', roomNo: 'H2-101', date: '2026-09-03', breakfast: true, lunch: true, snacks: true, dinner: true, totalPresent: 4, totalMeals: 4, hostelBlock: 'Hostel 2 (Boys)' },
  {
    id: 'att-1',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    rollNo: 'CS2023-014',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block A (Boys)'
  },
  {
    id: 'att-2',
    studentId: 'std-2',
    studentName: 'Diya Patel',
    rollNo: 'EC2023-088',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block G (Girls)'
  },
  {
    id: 'att-3',
    studentId: 'std-3',
    studentName: 'Rohan Verma',
    rollNo: 'ME2022-031',
    date: '2026-09-16',
    breakfast: false,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block B (Boys)'
  },
  {
    id: 'att-4',
    studentId: 'std-4',
    studentName: 'Ananya Iyer',
    rollNo: 'CS2024-009',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block G (Girls)'
  },
  {
    id: 'att-5',
    studentId: 'std-5',
    studentName: 'Vikramaditya Singh',
    rollNo: 'EE2023-045',
    date: '2026-09-16',
    breakfast: true,
    lunch: false,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block A (Boys)'
  },
  {
    id: 'att-6',
    studentId: 'std-6',
    studentName: 'Sneha Kulkarni',
    rollNo: 'CV2023-019',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block H (Girls)'
  },
  {
    id: 'att-7',
    studentId: 'std-7',
    studentName: 'Karan Mehra',
    rollNo: 'CS2023-062',
    date: '2026-09-16',
    breakfast: false,
    lunch: false,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block B (Boys)'
  },
  {
    id: 'att-8',
    studentId: 'std-8',
    studentName: 'Pooja Nair',
    rollNo: 'BT2024-002',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block G (Girls)'
  },
  {
    id: 'att-9',
    studentId: 'std-9',
    studentName: 'Aditya Gupta',
    rollNo: 'ME2023-054',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block C (Boys)'
  },
  {
    id: 'att-10',
    studentId: 'std-10',
    studentName: 'Ishaan Malhotra',
    rollNo: 'CS2022-071',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block A (Boys)'
  },
  {
    id: 'att-11',
    studentId: 'std-11',
    studentName: 'Tanvi Deshmukh',
    rollNo: 'CH2023-011',
    date: '2026-09-16',
    breakfast: true,
    lunch: false,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block H (Girls)'
  },
  {
    id: 'att-12',
    studentId: 'std-12',
    studentName: 'Manish Rawat',
    rollNo: 'EE2024-032',
    date: '2026-09-16',
    breakfast: false,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block C (Boys)'
  },
  {
    id: 'att-13',
    studentId: 'std-13',
    studentName: 'Rhea Sen',
    rollNo: 'EC2023-024',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block G (Girls)'
  },
  {
    id: 'att-14',
    studentId: 'std-14',
    studentName: 'Gaurav Joshi',
    rollNo: 'CS2023-099',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block B (Boys)'
  },
  {
    id: 'att-15',
    studentId: 'std-15',
    studentName: 'Neha Choudhary',
    rollNo: 'CV2022-044',
    date: '2026-09-16',
    breakfast: false,
    lunch: false,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block H (Girls)'
  },
  {
    id: 'att-16',
    studentId: 'std-16',
    studentName: 'Siddharth Rao',
    rollNo: 'ME2024-018',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block A (Boys)'
  },
  {
    id: 'att-17',
    studentId: 'std-17',
    studentName: 'Meera Nambiar',
    rollNo: 'BT2023-015',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block G (Girls)'
  },
  {
    id: 'att-18',
    studentId: 'std-18',
    studentName: 'Prateek Jain',
    rollNo: 'CS2023-118',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block B (Boys)'
  },
  {
    id: 'att-19',
    studentId: 'std-19',
    studentName: 'Simran Gill',
    rollNo: 'EC2024-006',
    date: '2026-09-16',
    breakfast: true,
    lunch: true,
    snacks: true,
    dinner: false,
    hostelBlock: 'Block H (Girls)'
  },
  {
    id: 'att-20',
    studentId: 'std-20',
    studentName: 'Harsh Vardhan',
    rollNo: 'EE2022-089',
    date: '2026-09-16',
    breakfast: true,
    lunch: false,
    snacks: false,
    dinner: false,
    hostelBlock: 'Block C (Boys)'
  }
];

export const INITIAL_SETTINGS: MessSettings = {
  messName: 'Hostel 2 Dining Mess',
  collegeName: 'GEC Sheikhpura',
  hostelBlocks: ['Hostel 2 (Boys)', 'Hostel 1', 'Hostel 3'],
  defaultMealRate: 45,
  latePaymentFee: 150,
  timings: [
    { meal: 'Breakfast', startTime: '07:30', endTime: '09:30', active: true },
    { meal: 'Lunch', startTime: '12:30', endTime: '14:30', active: true },
    { meal: 'Snacks', startTime: '17:00', endTime: '18:30', active: true },
    { meal: 'Dinner', startTime: '20:00', endTime: '22:00', active: true }
  ],
  allowMessCut: true,
  messCutMinHours: 48
};
